### ISSUE TITLE
Hide comments option

### ISSUE THREAD

**Issue by mjabv** [Appccessibility-Shox/Focus-for-YouTube#16]
All the current features are good except it's missing an option to remove comments

**Comment by joergister** [comment]
actually this option exists as can be seen on this screenshot.
<img width="692" alt="comments screenshot" src="https://user-images.githubusercontent.com/24881413/134648381-eaf2ca35-6169-4a39-955d-e92fc334b2a9.png">

**Comment by patrickshox** [comment]
Yep
