### ISSUE TITLE
Hide YouTube Thumbnails

### ISSUE THREAD

**Issue by pope52** [Appccessibility-Shox/Focus-for-YouTube#24]
I may be the minority on this, but it would be nice to have an option to hide YouTube thumbnails (or, alternatively, an advanced feature that lets the user manually input css elements to hide).

Thanks for your work on this.

**Comment by george-botros** [comment]
Great suggestion, @pope52. This has now been implemented.
https://github.com/Appccessibility-Shox/Focus-for-YouTube/blob/23b00fbf2a7cce4198c30b4f634a7c4cf14b6426/Focus%20for%20YouTube/ViewController.swift#L47
You can expect this new feature to be available in the next few days.
