### ISSUE TITLE
[Suggestion] Hide Youtube Shorts

### ISSUE THREAD

**Issue by ethanwayman** [Appccessibility-Shox/Focus-for-YouTube#25]

**Comment by sincerelyzhen** [comment]
I second this.

**Comment by george-botros** [comment]
Thanks for the suggestion, @ethanwayman. This has now been implemented.
https://github.com/Appccessibility-Shox/Focus-for-YouTube/blob/23b00fbf2a7cce4198c30b4f634a7c4cf14b6426/Focus%20for%20YouTube/ViewController.swift#L48
