### ISSUE TITLE
Shorts removal?

### ISSUE THREAD

**Issue by sincerelyzhen** [Appccessibility-Shox/Focus-for-YouTube#29]
Ability to remove shorts?

**Comment by daimuhiraoka** [comment]
Youtube shorts not removed with latest software on macbookair

**Comment by sincerelyzhen** [comment]
Looks like the developer has stopped updating the program. The only main problem is the explore, trending removal. And having this available on iPadOS. Otherwise the developer created an amazing program for YouTube.
