### ISSUE TITLE
Thumbnails still show up when blocked

### ISSUE THREAD

**Issue by aranbrancato** [Appccessibility-Shox/Focus-for-YouTube#41]
Everything else works for me at the moment, thumbnails have just reappeared.

<img width="824" alt="Screenshot 2022-11-28 at 12 36 38" src="https://user-images.githubusercontent.com/72361004/204354678-1c72befc-802b-48c8-8a41-4b39d1867aa1.png">

**Comment by george-botros** [comment]
Thank you for bringing this to our attention! This bug will be fixed in the next release.
