### ISSUE TITLE
[Suggestion/Improvement] Centering the video, about section and page content

### ISSUE THREAD

**Issue by joaopjoaopjoaop** [Appccessibility-Shox/Focus-for-YouTube#44]
It would be really nice if the focus extension also centered the remaining page elements on YouTube instead of leaving a big blank space in the right side.

For example, here's the Unhook for Chrome extension. 

[Focus For Youtube Screenshot](https://drive.google.com/file/d/1e_GAg62-w5LkDB8ow_VLvQxuulUjdAPU/view?usp=sharing)
[Unhook For Chrome Screenshot](https://drive.google.com/file/d/1VsCBtR2W8ookhVMQ7sDrZXPp2jPd7QAJ/view?usp=sharing)

**Comment by joaosjoaosjoaos** [comment]
I don't know much about extensions but I thought it might help that if you delete this part of the html code, the content is centered. The player is a little bit offset but a quick fix would be to use theater mode.
[Video Example](https://drive.google.com/file/d/191qjf53Zi8kfi3QDzKOR8wtZtMEEpril/view?usp=sharing)

**Comment by george-botros** [comment]
Merging with #31

**Comment by EugeneTarasenko** [comment]
Any progress?
