### ISSUE TITLE
[Bug] Even if I want to remove the Subscriptions, I still see them in Safari.

### ISSUE THREAD

**Issue by OshFrosch** [Appccessibility-Shox/Focus-for-YouTube#45]
Those are my Settings:
<img width="893" alt="Bildschirm­foto 2023-01-26 um 10 35 53" src="https://user-images.githubusercontent.com/44783000/214803206-fb2cc29a-771e-41d3-96d8-af428e8ab6ce.png">

And this is still my view:
<img width="1912" alt="Bildschirm­foto 2023-01-26 um 10 36 15" src="https://user-images.githubusercontent.com/44783000/214803269-ddf2102a-562c-42c6-a9d1-3619bd0399db.png">

**Comment by george-botros** [comment]
Thank you for bringing this to our attention! This bug will be fixed in the next release.
