### ISSUE TITLE
[Suggestion] Hide 'You' & 'YouTube Music' and 'Subscription list' from sidebar

### ISSUE THREAD

**Issue by PlanetPhilip** [Appccessibility-Shox/Focus-for-YouTube#57]
<img width="1368" alt="Screenshot 2023-09-26 at 13 50 35" src="https://github.com/Appccessibility-Shox/Focus-for-YouTube/assets/97726581/0dc896a8-4b25-437a-b82e-8d6155923b97">

Please Allow the ability to hide the 'You' tab from the sidebar, or at least hide the rows it contains: 'your channel', 'history' etc. and hide the 'YouTube Music' tab from the sidebar as well. 

I use the "Subscriptions' button at the top of the sidebar, but I don't want to see all the channels im subscribed to below it. The current feature to 'hide subscriptions', hides both. would it be possible to unlink them so they can be hidden separately ?

**Comment by george-botros** [comment]
"You" sidebar will be blockable in the next update. Thank you for the suggestion! Also, you should already be able to hide the subscription sidebar. https://github.com/Appccessibility-Shox/Focus-for-YouTube/commit/8d9aaa620f4a13fe3fd8bf9af62ed72cb07cf4eb
