### ISSUE TITLE
(suggestion) I would really like to hide the bar on the left that shows subscriptions etc.

### ISSUE THREAD

**Issue by waswerte** [Appccessibility-Shox/Focus-for-YouTube#61]

**Comment by george-botros** [comment]
You can do so by selecting the below options. We're also allowing users to hide the "You" sidebar in the next update.

<img width="319" alt="Screenshot 2024-01-19 at 5 43 21 PM" src="https://github.com/Appccessibility-Shox/Focus-for-YouTube/assets/78520093/7c38d498-1110-485b-bca3-77a381343406">
