### ISSUE TITLE
(issue report) thumbnail images not hidden

### ISSUE THREAD

**Issue by 1bulf** [Appccessibility-Shox/Focus-for-YouTube#62]
Hello, I have checked the "thumbnail images" option and unchecked all others. I have also disabled all other extensions. The thumbnail images are only hidden in:
history
channel home screen
embedded video in a channel community post

the thumbnail images are still visible in:
home screen
subscriptions
my playlists
channel video 
channel playlists screen
channel live screen
channel podcasts screen

**Comment by george-botros** [comment]
Should be fixed in next update. Thanks for bringing this to our attention! https://github.com/Appccessibility-Shox/Focus-for-YouTube/commit/29390ce4d5865b5f09e40b088f0669249a0ba8ee
