### ISSUE TITLE
Block shorts in search results

### ISSUE THREAD

**Issue by AG-Alangalura** [Appccessibility-Shox/Focus-for-YouTube#65]
YT inserts multiple shorts sections in the search results page. please have an option to block them, thanks

**Comment by george-botros** [comment]
Fixed in next update. Thank you for bringing this to our attention! https://github.com/Appccessibility-Shox/Focus-for-YouTube/commit/8d9aaa620f4a13fe3fd8bf9af62ed72cb07cf4eb
